/*
 * SH_Lara.h
 *
 *  Created on: 12.11.2015
 *      Author: T4Larson
 */

#ifndef SH_LARA_H_
#define SH_LARA_H_

#include "EntityStateHandler.h"
#include "entity.h"


class SH_Lara : public EntityStateHandler
{
protected:
    SH_Lara(Entity* pEnt)
    : EntityStateHandler(pEnt)
    {}
public:
    enum ID
    {
        WALK                 = 0,
        RUN                  = 1,
        STOP                 = 2,
        JUMP_FORWARD         = 3,
        POSE                 = 4,
        FASTBACK             = 5,
        TURN_RIGHT           = 6,
        TURN_LEFT            = 7,
        DEATH                = 8,
        FASTFALL             = 9,
        HANG                 = 10,
        REACH                = 11,
        SPLAT                = 12,
        UW_IDLE              = 13,
        GRAB_TO_FALL         = 14,
        JUMP_PREPARE         = 15,
        BACK                 = 16,
        UW_FORWARD           = 17,
        UW_GLIDE             = 18,
        CLIMB_DUMMY          = 19,
        TURN_FAST            = 20,
        STEP_RIGHT           = 21,
        STEP_LEFT            = 22,
        ROLL_CONTINUE        = 23,
        SLIDE_FORWARD        = 24,
        JUMP_BACK            = 25,
        JUMP_LEFT            = 26,
        JUMP_RIGHT           = 27,
        JUMP_UP              = 28,
        FALL_BACK            = 29,
        SHIMMY_LEFT          = 30,
        SHIMMY_RIGHT         = 31,
        SLIDE_BACK           = 32,
        SURF_SWIM_IDLE       = 33,
        SURF_SWIM_FORWARD    = 34,
        DIVE                 = 35,
        PUSHABLE_PUSH        = 36,
        PUSHABLE_PULL        = 37,
        PUSHABLE_GRAB        = 38,
        PICKUP               = 39,
        SWITCH_ON            = 40,
        SWITCH_OFF           = 41,
        USE_KEY              = 42,
        USE_PUZZLE           = 43,
        UW_DEATH             = 44,
        ROLL                 = 45,
        BOULDER_DEATH        = 46,
        SURF_SWIM_BACK       = 47,
        SURF_SWIM_LEFT       = 48,
        SURF_SWIM_RIGHT      = 49,
        USE_MIDAS            = 50,
        DIE_MIDAS            = 51,
        SWANDIVE             = 52,
        SWANDIVE_FALL        = 53,
        HANDSTAND            = 54,
        SURF_EXIT            = 55,
        WALL_CLIMB_IDLE      = 56,
        WALL_CLIMB_UP        = 57,
        WALL_CLIMB_LEFT      = 58,
        WALL_CLIMB_END       = 59,
        WALL_CLIMB_RIGHT     = 60,
        WALL_CLIMB_DOWN      = 61,
        WADE                 = 65,
        UW_TURN_ROLL         = 66,
        PICKUP_FLARE         = 67,
        JUMP_ROLL            = 68,
        ZIPLINE_RIDE         = 70,
        DUCK                 = 71,
        DUCKROLL             = 72,
        DASH                 = 73,
        DASHDIVE             = 74,
        MONKEY_IDLE          = 75,
        MONKEY_FWD           = 76,
        MONKEY_SHIMMY_LEFT   = 77,
        MONKEY_SHIMMY_RIGHT  = 78,
        MONKEY_TURN180       = 79,
        CRAWL_IDLE           = 80,
        CRAWL                = 81,
        MONKEY_TURN_LEFT     = 82,
        MONKEY_TURN_RIGHT    = 83,
        CRAWL_TURN_LEFT      = 84,
        CRAWL_TURN_RIGHT     = 85,
        CRAWL_BACK           = 86,
        CLIMB_TO_CRAWL       = 87,
        CRAWL_TO_CLIMB       = 88,
        GENERIC_ANIM_ACTION  = 89,
        ROPE_TURN_LEFT       = 90,
        ROPE_TURN_RIGHT      = 91,
        BLOCKSWITCH          = 92,
        TRAPDOOR_FLOOR_OPEN  = 93,
        USE_TURN_SWITCH      = 95,
        USE_COG_SWITCH       = 96,
        USE_RAIL_SWITCH      = 97,
        PICKUP_HOLE          = 98,
        POLE_IDLE            = 99,
        POLE_UP              = 100,
        POLE_DOWN            = 101,
        POLE_TURN_LEFT       = 102,
        POLE_TURN_RIGHT      = 103,
        PULLEY               = 104,
        DUCK_TURN_LEFT       = 105,
        DUCK_TURN_RIGHT      = 106,
        CORNER_OUTER_LEFT    = 107,
        CORNER_OUTER_RIGHT   = 108,
        CORNER_INNER_LEFT    = 109,
        CORNER_INNER_RIGHT   = 110,
        ROPE_IDLE            = 111,
        ROPE_UP              = 112,
        ROPE_DOWN            = 113,
        ROPE_SWING_FORWARD   = 114,
        ROPE_SWING_BACK      = 115,
        ROPE_DUMMY           = 116,
        PUSH_DOUBLE_DOORS    = 117,
        DOZY                 = 118,
        TIGHTROPE_IDLE       = 119,
        TIGHTROPE_TURN       = 120,
        TIGHTROPE_FORWARD    = 121,
        TIGHTROPE_FALL_LEFT  = 122,
        TIGHTROPE_FALL_RIGHT = 123,
        TIGHTROPE_ENTER      = 124,
        TIGHTROPE_EXIT       = 125,
        DOVESWITCH           = 126,
        TIGHTROPE_RECOVER    = 127,
        BARS_SWING           = 128,
        BARS_JUMP            = 129,
        RADIO_LISTENING      = 131,
        RADIO_OFF            = 132,
        PICKUP_FROM_CHEST    = 137,
    };

    static EntityStateHandler* createInstance(Entity*);
};

#endif /* SH_LARA_H_ */
